// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyheiBbaTLferuhIy6VDe2g595eRDWNI0',
    appId: '1:474547297960:web:37758ab919b4f1e5092c9d',
    messagingSenderId: '474547297960',
    projectId: 'app1-acca3',
    authDomain: 'app1-acca3.firebaseapp.com',
    databaseURL: 'https://app1-acca3-default-rtdb.firebaseio.com',
    storageBucket: 'app1-acca3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkKq9Vo00lc4orfN1t287Vxz1-6LEcFqk',
    appId: '1:474547297960:android:62eea610f441a7fd092c9d',
    messagingSenderId: '474547297960',
    projectId: 'app1-acca3',
    databaseURL: 'https://app1-acca3-default-rtdb.firebaseio.com',
    storageBucket: 'app1-acca3.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK-jyvRMIXbfV1lJAkHimC7pLQpjv0iCI',
    appId: '1:474547297960:ios:537f0b91924a645d092c9d',
    messagingSenderId: '474547297960',
    projectId: 'app1-acca3',
    databaseURL: 'https://app1-acca3-default-rtdb.firebaseio.com',
    storageBucket: 'app1-acca3.firebasestorage.app',
    iosBundleId: 'com.example.appNueva',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK-jyvRMIXbfV1lJAkHimC7pLQpjv0iCI',
    appId: '1:474547297960:ios:537f0b91924a645d092c9d',
    messagingSenderId: '474547297960',
    projectId: 'app1-acca3',
    databaseURL: 'https://app1-acca3-default-rtdb.firebaseio.com',
    storageBucket: 'app1-acca3.firebasestorage.app',
    iosBundleId: 'com.example.appNueva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyheiBbaTLferuhIy6VDe2g595eRDWNI0',
    appId: '1:474547297960:web:31a56576acfaadeb092c9d',
    messagingSenderId: '474547297960',
    projectId: 'app1-acca3',
    authDomain: 'app1-acca3.firebaseapp.com',
    databaseURL: 'https://app1-acca3-default-rtdb.firebaseio.com',
    storageBucket: 'app1-acca3.firebasestorage.app',
  );

}